/* Forge Game Center — Forge Control Center v6 */
(() => {
'use strict';
const SUPABASE_URL='https://pveivfqmeuswycgmpnue.supabase.co';
const SUPABASE_KEY='sb_publishable_Qpuk0Q-UsRKUP0jNgkzvAA_MymEGzQ8';
const CDNS=['https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js','https://unpkg.com/@supabase/supabase-js@2/dist/umd/supabase.min.js'];
const defaultGames={cyber:{name:'Cyber Detective',image:'assets/cyber-detective.png',status:'available',url:'https://jogos-forge.onrender.com'},pet:{name:'Forge Pet',image:'assets/forge-pet.png',status:'updating',url:'#'},hangman:{name:'Hangman Pro',image:'assets/hangman-pro.png',status:'available',url:'https://hangman-pro-jbdl.onrender.com'},words:{name:'Palavras Ocultas',image:'assets/palavras-ocultas.png',status:'updating',url:'#'}};
const labels={available:['PRONTO','O jogo está disponível para jogar.'],updating:['ATUALIZANDO','O jogo está recebendo atualizações.'],soon:['EM BREVE','O jogo está sendo preparado.'],offline:['INDISPONÍVEL','O jogo está temporariamente indisponível.']};
let sb=null,games=clone(defaultGames),maintenance={enabled:false,title:'Estamos em manutenção',message:'Estamos realizando algumas melhorias no Forge Game Center. Voltaremos logo.',returnAt:'',button:'Aguardar retorno'},channel=null;
let cache={ideas:[],news:[],roadmap:[],announcements:[],logs:[]};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function clone(o){return JSON.parse(JSON.stringify(o))} function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function runtime(m,e=false){const x=$('#adminRuntimeMessage');if(x){x.textContent=m;x.className='admin-feedback runtime-message'+(e?' error':'')}}
function authMsg(m,e=false){const x=$('#adminAuthMessage');if(x){x.textContent=m;x.className='admin-feedback'+(e?' error':'')}}
function sync(m){const x=$('#syncStatus');if(x)x.textContent=m}
function visible(v){$('#adminControls').hidden=!v;$('#adminLogin').hidden=v}
function loadScript(src){return new Promise((res,rej)=>{const s=document.createElement('script');s.src=src;s.async=true;s.onload=res;s.onerror=()=>rej(new Error('Falha ao carregar '+src));document.head.appendChild(s)})}
async function ensureSB(){if(window.supabase?.createClient)return window.supabase;let e;for(const c of CDNS){try{await loadScript(c);if(window.supabase?.createClient)return window.supabase}catch(x){e=x}}throw e||new Error('Biblioteca Supabase não carregou.')}
function friendly(e){const m=String(e?.message||'').toLowerCase();if(m.includes('invalid login'))return'E-mail ou senha incorretos.';if(m.includes('already registered'))return'Este e-mail já possui uma conta.';if(m.includes('not confirmed'))return'Confirme o e-mail antes de entrar.';if(m.includes('rate limit'))return'Limite temporário de e-mails atingido.';return e?.message||'Erro no Supabase.'}
async function boot(){try{runtime('Conectando ao Supabase…');const lib=await ensureSB();sb=lib.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});wire();sync('● Conectado');await initAdmin();runtime('Painel carregado.')}catch(e){sync('● Erro');runtime('Erro ao iniciar: '+e.message,true)}}
async function currentAdmin(){if(!sb)return null;const {data:{session},error}=await sb.auth.getSession();if(error||!session){visible(false);$('#claimAdminBtn').hidden=true;return null}const {data,error:e}=await sb.from('forge_admin_users').select('user_id').eq('user_id',session.user.id).maybeSingle();if(e){visible(false);authMsg('Erro ao verificar administrador: '+e.message,true);return null}if(!data){visible(false);$('#claimAdminBtn').hidden=false;authMsg('Conta autenticada. Ative o primeiro administrador.');return null}$('#claimAdminBtn').hidden=true;visible(true);$('#adminUserLabel').textContent=session.user.email||'Administrador';return session.user}
async function login(){const email=$('#adminEmail').value.trim(),password=$('#adminPassword').value;if(!email||!password)return authMsg('Informe e-mail e senha.',true);sync('● Autenticando…');const {error}=await sb.auth.signInWithPassword({email,password});if(error){sync('● Erro');return authMsg(friendly(error),true)}await initAdmin()}
async function signup(){const email=$('#adminEmail').value.trim(),password=$('#adminPassword').value;if(!email||password.length<6)return authMsg('Informe e-mail e uma senha com pelo menos 6 caracteres.',true);sync('● Criando conta…');const {data,error}=await sb.auth.signUp({email,password});if(error)return authMsg(friendly(error),true);if(!data.session)return authMsg('✓ Conta criada. Confirme o e-mail e depois entre novamente.');await initAdmin()}
async function claim(){const {data:{session}}=await sb.auth.getSession();if(!session)return authMsg('Entre antes de ativar o administrador.',true);sync('● Ativando…');const {data,error}=await sb.rpc('forge_claim_first_admin');if(error)return authMsg('Não foi possível ativar: '+error.message,true);if(data===true){authMsg('✓ Primeiro administrador ativado.');await initAdmin()}else authMsg('Já existe um administrador.')}
async function logout(){await sb.auth.signOut();location.reload()}
function nav(){ $$('.admin-nav').forEach(b=>b.addEventListener('click',()=>{ $$('.admin-nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.admin-section').forEach(s=>s.classList.remove('active'));$('#section-'+b.dataset.section).classList.add('active');if(b.dataset.section==='ideas')loadIdeas();if(b.dataset.section==='news')loadNews();if(b.dataset.section==='roadmap')loadRoadmap();if(b.dataset.section==='announcements')loadAnnouncements();if(b.dataset.section==='logs')loadLogs();if(b.dataset.section==='control')diagnostics()})) }
function wire(){ $('#adminLoginBtn').onclick=login;$('#adminSignupBtn').onclick=signup;$('#claimAdminBtn').onclick=claim;$('#adminLogoutBtn').onclick=logout;$('#adminPassword').onkeydown=e=>{if(e.key==='Enter')login()};nav();$('#refreshAll').onclick=loadAll;$('#resetGames').onclick=resetGames;$('#saveMaintenance').onclick=saveMaintenance;$('#maintenanceEnabled').onchange=saveMaintenance;$('#refreshIdeas').onclick=loadIdeas;$('#newNews').onclick=()=>newsModal();$('#newRoadmap').onclick=()=>roadmapModal();$('#newAnnouncement').onclick=()=>announcementModal();$('#refreshLogs').onclick=loadLogs;$('#runDiagnostics').onclick=diagnostics;sb.auth.onAuthStateChange((ev)=>{if(['SIGNED_IN','SIGNED_OUT','TOKEN_REFRESHED'].includes(ev))setTimeout(initAdmin,50)}) }
async function initAdmin(){const u=await currentAdmin();if(!u)return;await loadAll();subscribe()}
async function loadAll(){sync('● Sincronizando…');const [g,m]=await Promise.all([sb.from('forge_game_status').select('*').order('game_id'),sb.from('forge_site_settings').select('*').eq('id','main').single()]);if(g.error||m.error){sync('● Erro');return authMsg('Erro ao carregar dados: '+(g.error||m.error).message,true)}games={};(g.data||[]).forEach(r=>games[r.game_id]=r);maintenance={enabled:m.data.maintenance_enabled,title:m.data.maintenance_title,message:m.data.maintenance_message,returnAt:m.data.maintenance_return_at||'',button:m.data.maintenance_button||''};renderGames();fillMaintenance();renderDashboard();await Promise.all([loadIdeas(true),loadNews(true),loadRoadmap(true),loadAnnouncements(true),loadLogs(true)]);sync('● Sincronizado')}
function renderGames(){const box=$('#gameControls');box.innerHTML=Object.entries(games).map(([id,g])=>{const [lab,desc]=labels[g.status]||labels.updating;return `<article class="game-control"><img src="${esc(g.image)}" alt=""><div class="gc-info"><strong>${esc(g.name)}</strong><small>${esc(desc)}</small><small class="gc-url">${esc(g.url||'Sem URL')}</small></div><div class="gc-actions"><span class="gc-state ${esc(g.status)}">${lab}</span><select data-game="${id}"><option value="available" ${g.status==='available'?'selected':''}>Pronto</option><option value="updating" ${g.status==='updating'?'selected':''}>Atualizando</option><option value="soon" ${g.status==='soon'?'selected':''}>Em breve</option><option value="offline" ${g.status==='offline'?'selected':''}>Indisponível</option></select></div></article>`}).join('');box.querySelectorAll('select').forEach(s=>s.onchange=()=>updateGame(s.dataset.game,s.value));$('#dashboardGames').innerHTML=Object.values(games).map(g=>`<div class="mini-game"><img src="${esc(g.image)}"><div><b>${esc(g.name)}</b><small class="gc-state ${g.status}">${labels[g.status]?.[0]||g.status}</small></div></div>`).join('')}
async function updateGame(id,status){const g=games[id];sync('● Salvando…');const {error}=await sb.from('forge_game_status').update({status}).eq('game_id',id);if(error)return authMsg('Erro ao salvar: '+error.message,true);await log(`Status de ${g.name} → ${labels[status][0]}`,'game',id);await loadAll()}
function fillMaintenance(){$('#maintenanceEnabled').checked=!!maintenance.enabled;$('#maintenanceTitle').value=maintenance.title||'';$('#maintenanceMessage').value=maintenance.message||'';$('#maintenanceReturn').value=maintenance.returnAt?new Date(maintenance.returnAt).toISOString().slice(0,16):'';$('#maintenanceButton').value=maintenance.button||'';previewMaintenance()}
function previewMaintenance(){const box=$('#maintenancePreview');if(!box)return;box.innerHTML=`<div class="preview-icon">🛠️</div><h3>${esc($('#maintenanceTitle')?.value||maintenance.title)}</h3><p>${esc($('#maintenanceMessage')?.value||maintenance.message)}</p><small>${$('#maintenanceReturn')?.value?'Previsão: '+new Date($('#maintenanceReturn').value).toLocaleString('pt-BR'):''}</small>`}
async function saveMaintenance(){const p={maintenance_enabled:$('#maintenanceEnabled').checked,maintenance_title:$('#maintenanceTitle').value.trim()||'Estamos em manutenção',maintenance_message:$('#maintenanceMessage').value.trim()||'Voltaremos logo.',maintenance_return_at:$('#maintenanceReturn').value?new Date($('#maintenanceReturn').value).toISOString():null,maintenance_button:$('#maintenanceButton').value.trim()||'Aguardar retorno'};sync('● Salvando…');const {error}=await sb.from('forge_site_settings').update(p).eq('id','main');if(error)return authMsg('Erro: '+error.message,true);maintenance={enabled:p.maintenance_enabled,title:p.maintenance_title,message:p.maintenance_message,returnAt:p.maintenance_return_at,button:p.maintenance_button};$('#saveFeedback').textContent='✓ Salvo e sincronizado';previewMaintenance();await log(`Manutenção ${p.maintenance_enabled?'ativada':'desativada'}`,'maintenance','main');sync('● Sincronizado')}
['maintenanceTitle','maintenanceMessage','maintenanceReturn','maintenanceButton'].forEach(id=>document.addEventListener('input',e=>{if(e.target.id===id)previewMaintenance()}));
async function resetGames(){if(!confirm('Restaurar os status padrão dos jogos?'))return;for(const [id,g] of Object.entries(defaultGames))await sb.from('forge_game_status').update({status:g.status}).eq('game_id',id);await log('Status dos jogos restaurados','game','all');loadAll()}
async function loadIdeas(silent=false){const {data,error}=await sb.from('forge_ideas').select('*').order('created_at',{ascending:false});if(error){if(!silent)authMsg(error.message,true);return}cache.ideas=data||[];$('#ideasBadge').textContent=cache.ideas.filter(x=>x.status==='new').length;$('#ideasList').innerHTML=cache.ideas.length?cache.ideas.map(i=>`<article class="data-card"><div><span class="tag">${esc(i.idea_type)}</span><h3>${esc(i.title)}</h3><p>${esc(i.description)}</p><small>${esc(i.author_name||'Jogador')} · ${new Date(i.created_at).toLocaleString('pt-BR')}</small></div><select onchange="window.forgeIdeaStatus(${i.id},this.value)">${['new','reviewing','approved','development','implemented','rejected'].map(s=>`<option value="${s}" ${i.status===s?'selected':''}>${s}</option>`).join('')}</select></article>`).join(''):'<div class="empty-panel">💡 Nenhuma ideia cadastrada ainda.</div>';renderDashboard()}
window.forgeIdeaStatus=async(id,status)=>{const {error}=await sb.from('forge_ideas').update({status}).eq('id',id);if(error)return authMsg(error.message,true);await log(`Ideia #${id} → ${status}`,'idea',String(id));loadIdeas()}
async function loadNews(silent=false){const {data,error}=await sb.from('forge_news').select('*').order('created_at',{ascending:false});if(error){if(!silent)authMsg(error.message,true);return}cache.news=data||[];$('#newsList').innerHTML=cache.news.length?cache.news.map(n=>`<article class="data-card"><div><span class="tag ${n.published?'success':''}">${n.published?'PUBLICADA':'RASCUNHO'}</span><h3>${esc(n.title)}</h3><p>${esc(n.content)}</p><small>${new Date(n.created_at).toLocaleString('pt-BR')}</small></div><div class="row-actions"><button class="admin-secondary" onclick="window.forgeEditNews(${n.id})">Editar</button><button class="admin-danger" onclick="window.forgeDeleteNews(${n.id})">Excluir</button></div></article>`).join(''):'<div class="empty-panel">📰 Nenhuma notícia cadastrada.</div>'}
window.forgeEditNews=id=>newsModal(cache.news.find(x=>x.id===id));window.forgeDeleteNews=async id=>{if(!confirm('Excluir esta notícia?'))return;await sb.from('forge_news').delete().eq('id',id);await log(`Notícia #${id} excluída`,'news',String(id));loadNews()}
function newsModal(item={}){openModal(`<div class="modal-card"><button class="modal-close" onclick="window.closeForgeModal()">×</button><h2>${item.id?'Editar':'Nova'} notícia</h2><label>Título<input id="mNewsTitle" value="${esc(item.title||'')}"></label><label>Conteúdo<textarea id="mNewsContent">${esc(item.content||'')}</textarea></label><label>Imagem (opcional)<input id="mNewsImage" value="${esc(item.image||'')}"></label><label class="check-row"><input id="mNewsPublished" type="checkbox" ${item.published?'checked':''}> Publicar agora</label><button class="admin-primary" onclick="window.saveNews(${item.id||0})">Salvar</button></div>`)}
window.saveNews=async id=>{const p={title:$('#mNewsTitle').value.trim(),content:$('#mNewsContent').value.trim(),image:$('#mNewsImage').value.trim()||null,published:$('#mNewsPublished').checked,published_at:$('#mNewsPublished').checked?new Date().toISOString():null};if(!p.title||!p.content)return alert('Preencha título e conteúdo.');const q=id?sb.from('forge_news').update(p).eq('id',id):sb.from('forge_news').insert(p);const {error}=await q;if(error)return alert(error.message);await log(`${id?'Notícia editada':'Notícia criada'}: ${p.title}`,'news',String(id||''));closeModal();loadNews()}
async function loadRoadmap(silent=false){const {data,error}=await sb.from('forge_roadmap').select('*').order('position');if(error){if(!silent)authMsg(error.message,true);return}cache.roadmap=data||[];$('#roadmapList').innerHTML=cache.roadmap.length?cache.roadmap.map(r=>`<article class="data-card"><div><span class="tag">${esc(r.period||'')}</span><h3>${esc(r.title)}</h3><p>${esc(r.description||'')}</p><small>${esc(r.status)} ${r.game_id?'· '+esc(r.game_id):''}</small></div><div class="row-actions"><button class="admin-secondary" onclick="window.forgeEditRoadmap(${r.id})">Editar</button><button class="admin-danger" onclick="window.forgeDeleteRoadmap(${r.id})">Excluir</button></div></article>`).join(''):'<div class="empty-panel">🚀 Roadmap vazio.</div>'}
window.forgeEditRoadmap=id=>roadmapModal(cache.roadmap.find(x=>x.id===id));window.forgeDeleteRoadmap=async id=>{if(!confirm('Excluir este item?'))return;await sb.from('forge_roadmap').delete().eq('id',id);await log(`Roadmap #${id} excluído`,'roadmap',String(id));loadRoadmap()}
function roadmapModal(item={}){openModal(`<div class="modal-card"><button class="modal-close" onclick="window.closeForgeModal()">×</button><h2>${item.id?'Editar':'Novo'} item do roadmap</h2><label>Título<input id="mRoadTitle" value="${esc(item.title||'')}"></label><label>Descrição<textarea id="mRoadDesc">${esc(item.description||'')}</textarea></label><label>Jogo<select id="mRoadGame"><option value="">Geral</option>${Object.entries(games).map(([id,g])=>`<option value="${id}" ${item.game_id===id?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label><label>Período<input id="mRoadPeriod" value="${esc(item.period||'')}"></label><label>Status<select id="mRoadStatus">${['planned','development','testing','launched'].map(s=>`<option ${item.status===s?'selected':''}>${s}</option>`).join('')}</select></label><button class="admin-primary" onclick="window.saveRoadmap(${item.id||0})">Salvar</button></div>`)}
window.saveRoadmap=async id=>{const p={title:$('#mRoadTitle').value.trim(),description:$('#mRoadDesc').value.trim(),game_id:$('#mRoadGame').value||null,period:$('#mRoadPeriod').value.trim(),status:$('#mRoadStatus').value};if(!p.title)return alert('Informe um título.');const q=id?sb.from('forge_roadmap').update(p).eq('id',id):sb.from('forge_roadmap').insert(p);const {error}=await q;if(error)return alert(error.message);await log(`${id?'Roadmap editado':'Roadmap criado'}: ${p.title}`,'roadmap',String(id||''));closeModal();loadRoadmap()}
async function loadAnnouncements(silent=false){const {data,error}=await sb.from('forge_announcements').select('*').order('created_at',{ascending:false});if(error){if(!silent)authMsg(error.message,true);return}cache.announcements=data||[];$('#announcementsList').innerHTML=cache.announcements.length?cache.announcements.map(a=>`<article class="data-card"><div><span class="tag ${a.active?'success':''}">${a.active?'ATIVO':'INATIVO'}</span><h3>${esc(a.title)}</h3><p>${esc(a.message)}</p><small>${esc(a.type)} ${a.expires_at?'· até '+new Date(a.expires_at).toLocaleString('pt-BR'):''}</small></div><div class="row-actions"><button class="admin-secondary" onclick="window.forgeEditAnnouncement(${a.id})">Editar</button><button class="admin-danger" onclick="window.forgeDeleteAnnouncement(${a.id})">Excluir</button></div></article>`).join(''):'<div class="empty-panel">🔔 Nenhum aviso cadastrado.</div>'}
window.forgeEditAnnouncement=id=>announcementModal(cache.announcements.find(x=>x.id===id));window.forgeDeleteAnnouncement=async id=>{if(!confirm('Excluir este aviso?'))return;await sb.from('forge_announcements').delete().eq('id',id);await log(`Aviso #${id} excluído`,'announcement',String(id));loadAnnouncements()}
function announcementModal(item={}){openModal(`<div class="modal-card"><button class="modal-close" onclick="window.closeForgeModal()">×</button><h2>${item.id?'Editar':'Novo'} aviso</h2><label>Título<input id="mAnnTitle" value="${esc(item.title||'')}"></label><label>Mensagem<textarea id="mAnnMessage">${esc(item.message||'')}</textarea></label><label>Tipo<select id="mAnnType">${['info','success','warning','maintenance'].map(s=>`<option ${item.type===s?'selected':''}>${s}</option>`).join('')}</select></label><label class="check-row"><input id="mAnnActive" type="checkbox" ${item.active!==false?'checked':''}> Ativo</label><label>Expira em (opcional)<input id="mAnnExpires" type="datetime-local" value="${item.expires_at?new Date(item.expires_at).toISOString().slice(0,16):''}"></label><button class="admin-primary" onclick="window.saveAnnouncement(${item.id||0})">Salvar</button></div>`)}
window.saveAnnouncement=async id=>{const p={title:$('#mAnnTitle').value.trim(),message:$('#mAnnMessage').value.trim(),type:$('#mAnnType').value,active:$('#mAnnActive').checked,expires_at:$('#mAnnExpires').value?new Date($('#mAnnExpires').value).toISOString():null};if(!p.title||!p.message)return alert('Preencha título e mensagem.');const q=id?sb.from('forge_announcements').update(p).eq('id',id):sb.from('forge_announcements').insert(p);const {error}=await q;if(error)return alert(error.message);await log(`${id?'Aviso editado':'Aviso criado'}: ${p.title}`,'announcement',String(id||''));closeModal();loadAnnouncements()}
async function loadLogs(silent=false){const {data,error}=await sb.from('forge_admin_logs').select('*').order('created_at',{ascending:false}).limit(50);if(error){if(!silent)authMsg(error.message,true);return}cache.logs=data||[];$('#logsList').innerHTML=cache.logs.length?cache.logs.map(l=>`<article class="data-card log-card"><div><span class="tag">${esc(l.entity_type)}</span><h3>${esc(l.action)}</h3><small>${new Date(l.created_at).toLocaleString('pt-BR')} ${l.entity_id?'· #'+esc(l.entity_id):''}</small></div></article>`).join(''):'<div class="empty-panel">📋 Nenhum log registrado ainda.</div>';renderDashboard()}
async function log(action,type,id=''){try{await sb.from('forge_admin_logs').insert({action,entity_type:type,entity_id:id||null})}catch(e){}}
function renderDashboard(){const counts={games:Object.keys(games).length,available:Object.values(games).filter(g=>g.status==='available').length,ideas:cache.ideas.length,news:cache.news.length,roadmap:cache.roadmap.length,announcements:cache.announcements.filter(a=>a.active).length};$('#metricGrid').innerHTML=[['🎮','Jogos',counts.games],['🟢','Disponíveis',counts.available],['💡','Ideias',counts.ideas],['📰','Notícias',counts.news],['🚀','Roadmap',counts.roadmap],['🔔','Avisos ativos',counts.announcements]].map(x=>`<div class="metric-card"><span>${x[0]}</span><small>${x[1]}</small><strong>${x[2]}</strong></div>`).join('');$('#statsGrid').innerHTML=$('#metricGrid').innerHTML;$('#recentLogs').innerHTML=cache.logs.slice(0,6).map(l=>`<div class="activity-item"><span>•</span><div><b>${esc(l.action)}</b><small>${new Date(l.created_at).toLocaleString('pt-BR')}</small></div></div>`).join('')||'<div class="empty-panel compact">Sem atividades registradas.</div>'}
function renderImages(){const imgs=Object.values(games);$('#imageGrid').innerHTML=imgs.map(g=>`<div class="image-admin-card"><img src="${esc(g.image)}"><b>${esc(g.name)}</b><small>${esc(g.image)}</small></div>`).join('')}
async function diagnostics(){const checks=[];try{const {error}=await sb.from('forge_game_status').select('game_id').limit(1);checks.push(['Banco Supabase',!error,error?.message||'OK'])}catch(e){checks.push(['Banco Supabase',false,e.message])}checks.push(['Sessão administrativa',true,'Autenticado']);checks.push(['Jogos',Object.keys(games).length===4,`${Object.keys(games).length} registros`]);checks.push(['Manutenção',true,maintenance.enabled?'ATIVADA':'DESATIVADA']);checks.push(['Forge Labs',true,`${cache.ideas.length} ideias`]);checks.push(['Notícias',true,`${cache.news.length} registros`]);checks.push(['Roadmap',true,`${cache.roadmap.length} itens`]);$('#diagnosticsGrid').innerHTML=checks.map(c=>`<div class="diagnostic-card"><span class="diag-dot ${c[1]?'ok':'bad'}"></span><div><b>${c[0]}</b><small>${esc(c[2])}</small></div></div>`).join('')}
function openModal(html){$('#modalRoot').innerHTML=`<div class="modal-backdrop">${html}</div>`}function closeModal(){$('#modalRoot').innerHTML=''}window.closeForgeModal=closeModal;
function subscribe(){if(channel)sb.removeChannel(channel);channel=sb.channel('forge-control-center').on('postgres_changes',{event:'*',schema:'public',table:'forge_game_status'},loadAll).on('postgres_changes',{event:'*',schema:'public',table:'forge_site_settings'},loadAll).on('postgres_changes',{event:'*',schema:'public',table:'forge_ideas'},()=>loadIdeas(true)).on('postgres_changes',{event:'*',schema:'public',table:'forge_news'},()=>loadNews(true)).on('postgres_changes',{event:'*',schema:'public',table:'forge_roadmap'},()=>loadRoadmap(true)).on('postgres_changes',{event:'*',schema:'public',table:'forge_announcements'},()=>loadAnnouncements(true)).subscribe();}
window.addEventListener('beforeunload',()=>{if(channel&&sb)sb.removeChannel(channel)});
document.addEventListener('DOMContentLoaded',()=>{boot();renderImages()},{once:true});
})();
